sudo: required
services:
  -docker

before_install:
  - docker build -t hessera/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run hessera/react-test npm test -- --coverage

after_success:
  - docker build -t hessera/multi-client ./client
  - docker build -t hessera/multi-nginx ./nginx
  - docker build -t hessera/multi-server ./server
  - docker build -t hessera/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take thoes images and push them to docker hub
  - docker push hessera/multi-client
  - docker push hessera/multi-nginx
  - docker push hessera/multi-server
  - docker push hessera/multi-worker
